#!/usr/bin/env python3
"""
Deployment script for Demo Research Team
Generated by Simple Team Builder
"""
import sys
import os
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.hierarchical.hierarchical_agent import HierarchicalAgentTeam
from src.core.hierarchical_config_loader import HierarchicalConfigLoader

def deploy_demoresearchteam():
    """Deploy the Demo Research Team hierarchical team."""
    
    # Load configuration
    config_file = Path(__file__).parent / "demoresearchteam_team.yml"
    
    if not config_file.exists():
        print(f"❌ Configuration file not found: {config_file}")
        return False
    
    try:
        # Load hierarchical configuration
        loader = HierarchicalConfigLoader()
        config = loader.load_config(str(config_file))
        
        # Create team instance
        team = HierarchicalAgentTeam(
            name="Demo Research Team",
            hierarchical_config=config.model_dump()
        )
        
        print(f"✅ Demo Research Team deployed successfully!")
        print(f"📊 Team Info: {team.get_hierarchy_info()}")
        
        return team
        
    except Exception as e:
        print(f"❌ Deployment failed: {e}")
        return False

def test_demoresearchteam(team, test_message: str = "Hello, team!"):
    """Test the deployed team."""
    try:
        print(f"🧪 Testing team with message: '{test_message}'")
        result = team.run(test_message)
        print(f"📋 Team Response: {result.get('response', 'No response')}")
        return result
    except Exception as e:
        print(f"❌ Test failed: {e}")
        return None

if __name__ == "__main__":
    # Deploy the team
    team = deploy_demoresearchteam()
    
    if team:
        # Interactive testing
        print("\n💬 Interactive Testing Mode")
        print("Type 'quit' to exit")
        
        while True:
            user_input = input("\nEnter test message: ").strip()
            if user_input.lower() in ['quit', 'exit', 'q']:
                break
            
            if user_input:
                test_demoresearchteam(team, user_input)
            
        print("👋 Goodbye!")
    else:
        print("❌ Deployment failed. Please check your configuration.")
        sys.exit(1)
